# Generated by Django 6.0.6 on 2026-06-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="주문번호"
                    ),
                ),
                (
                    "payment_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="PG 결제키"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "신용카드"),
                            ("kakaopay", "카카오페이"),
                            ("tosspay", "토스페이"),
                            ("naverpay", "네이버페이"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="결제 금액")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "결제 준비"),
                            ("done", "결제 완료"),
                            ("cancelled", "결제 취소"),
                            ("failed", "결제 실패"),
                        ],
                        default="ready",
                        max_length=10,
                    ),
                ),
                (
                    "pg_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="PG 응답 원본"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="결제 시각"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="취소 시각"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="이벤트 유형"),
                ),
                ("payload", models.JSONField(verbose_name="수신 데이터")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="처리 완료"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_logs",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
