# Generated by Django 6.0.6 on 2026-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="외부 이미지 URL (개발용)",
                verbose_name="썸네일 URL",
            ),
        ),
    ]
