# Generated by Django 6.0.6 on 2026-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activity_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="외부 이미지 URL (개발용)",
                max_length=500,
                verbose_name="썸네일 URL",
            ),
        ),
    ]
