# Generated by Django 6.0.6 on 2026-06-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("activities", "0003_alter_activity_thumbnail_url"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["status", "created_at"], name="idx_activity_status"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["partner"], name="idx_activity_partner"),
        ),
    ]
