# Generated by Django 6.0.6 on 2026-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_activity_idx_activity_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="description_ko",
            field=models.TextField(blank=True, verbose_name="상세 설명(한국어)"),
        ),
        migrations.AddField(
            model_name="activity",
            name="title_ko",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="제목(한국어)"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description_ko",
            field=models.TextField(blank=True, verbose_name="코스 설명(한국어)"),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ko",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="코스명(한국어)"
            ),
        ),
    ]
