# Generated by Django 6.0.6 on 2026-06-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("activities", "0005_activity_description_ko_activity_title_ko_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="address_ko",
            field=models.CharField(blank=True, max_length=300, verbose_name="주소(KO)"),
        ),
        migrations.AddField(
            model_name="activity",
            name="google_place_id",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                unique=True,
                verbose_name="Google Place ID",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="google_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                verbose_name="Google 평점",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="google_reviews_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Google 리뷰 수"),
        ),
        migrations.AddField(
            model_name="activity",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="전화번호"),
        ),
        migrations.AddField(
            model_name="activity",
            name="photo_urls",
            field=models.JSONField(blank=True, default=list, verbose_name="사진 URLs"),
        ),
        migrations.AddField(
            model_name="activity",
            name="website",
            field=models.URLField(blank=True, max_length=500, verbose_name="웹사이트"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="address",
            field=models.CharField(blank=True, max_length=300, verbose_name="주소(EN)"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="capacity",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="최대 정원"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True, verbose_name="설명(EN)"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description_ko",
            field=models.TextField(blank=True, verbose_name="설명(KO)"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="소요 시간 (분)"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="accounts.partner",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="가격 (원)"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "임시저장"),
                    ("pending", "심사 대기"),
                    ("approved", "승인"),
                    ("rejected", "반려"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="thumbnail_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="썸네일 URL"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="title",
            field=models.CharField(max_length=200, verbose_name="제목(EN)"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="title_ko",
            field=models.CharField(blank=True, max_length=200, verbose_name="제목(KO)"),
        ),
    ]
