# Generated by Django 6.0.6 on 2026-06-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_activity_address_ko_activity_google_place_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="google_reviews",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Google 리뷰"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="opening_hours",
            field=models.JSONField(blank=True, default=list, verbose_name="운영시간"),
        ),
    ]
