# Generated by Django 6.0.6 on 2026-06-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_activity_google_reviews_activity_opening_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="google_reviews_en",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Google 리뷰(EN)"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="google_reviews",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Google 리뷰(KO)"
            ),
        ),
    ]
