# Generated by Django 6.0.6 on 2026-06-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sales", models.PositiveIntegerField(verbose_name="총 매출액")),
                (
                    "platform_fee",
                    models.PositiveIntegerField(verbose_name="플랫폼 수수료"),
                ),
                (
                    "settlement_amount",
                    models.PositiveIntegerField(verbose_name="정산 금액"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "정산 예정"),
                            ("processing", "처리 중"),
                            ("completed", "정산 완료"),
                            ("failed", "정산 실패"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("period_start", models.DateField(verbose_name="정산 시작일")),
                ("period_end", models.DateField(verbose_name="정산 종료일")),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="정산 완료일"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bookings",
                    models.ManyToManyField(
                        related_name="settlements", to="bookings.booking"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="accounts.partner",
                    ),
                ),
            ],
            options={
                "db_table": "settlements",
                "ordering": ["-created_at"],
            },
        ),
    ]
