# Generated by Django 6.0.6 on 2026-06-17 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headcount",
                    models.PositiveSmallIntegerField(verbose_name="예약 인원"),
                ),
                ("total_amount", models.PositiveIntegerField(verbose_name="결제 금액")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "결제 대기"),
                            ("confirmed", "결제 완료"),
                            ("completed", "이용 완료"),
                            ("cancelled", "취소"),
                            ("refunded", "환불 완료"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "special_request",
                    models.TextField(blank=True, verbose_name="특별 요청사항"),
                ),
                (
                    "reservation_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="예약번호"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="activities.course",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="activities.activityslot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
