# Generated by Django 6.0.6 on 2026-06-19 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_activity_idx_activity_status_and_more"),
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="idx_booking_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="idx_booking_status"),
        ),
    ]
